### ISSUE TITLE
Error when running npm run make:release, the node used is v20.17.0 LTS

### ISSUE THREAD

**Issue by wildtang** [heliomarpm/electron-vuevite-quick-start#18]
Hi, yesterday, I cloned this repo and try to build this project, But failed.
Maybe has relations with node v20.17, Can you do some fix to it? Thanks.

```
PS E:\github.com\electron-vuevite-quick-start> git pull
Already up to date.

PS E:\github.com\electron-vuevite-quick-start> git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

PS E:\github.com\electron-vuevite-quick-start> npm install

added 376 packages, and audited 377 packages in 19s

61 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (4 moderate, 1 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

PS E:\github.com\electron-vuevite-quick-start> node --version
v20.17.0

PS E:\github.com\electron-vuevite-quick-start> npm run make:release

> electron-vuevite-quick-start@0.2.1 make:release
> node ./cmd/modules/release/index.js

E:\github.com\electron-vuevite-quick-start\cmd\modules\release\index.js:3
const open = require('open')
             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module E:\github.com\electron-vuevite-quick-start\node_modules\open\index.js from E:\github.com\electron-vuevite-quick-start\cmd\modules\release\index.js not supported.
Instead change the require of E:\github.com\electron-vuevite-quick-start\node_modules\open\index.js in E:\github.com\electron-vuevite-quick-start\cmd\modules\release\index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (E:\github.com\electron-vuevite-quick-start\cmd\modules\release\index.js:3:14) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.17.0
PS E:\github.com\electron-vuevite-quick-start>

```

**Comment by wildtang** [comment]
I tested Node.js v18.20.4 too, still has this problem.

```
/e/i/M/github.com ❱ cd electron-vuevite-quick-start/

/e/i/M/g/electron-vuevite-quick-start main• 2.2s ❱ nvm use v18.20.4
Now using node v18.20.4 (npm v10.7.0)

/e/i/M/g/electron-vuevite-quick-start main• 2.3s ❱ node --version
v18.20.4

/e/i/M/g/electron-vuevite-quick-start main• ❱ rm -rf ./node_modules/

/e/i/M/g/electron-vuevite-quick-start main• 2.7s ❱ npm install

added 376 packages in 43s

61 packages are looking for funding
  run `npm fund` for details

/e/i/M/g/electron-vuevite-quick-start main• 43.6s ❱ npm run make:release

> electron-vuevite-quick-start@0.2.1 make:release
> node ./cmd/modules/release/index.js

E:\inBackup\MyCode\github.com\electron-vuevite-quick-start\cmd\modules\release\index.js:3
const open = require('open')
             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module E:\inBackup\MyCode\github.com\electron-vuevite-quick-start\node_
modules\open\index.js from E:\inBackup\MyCode\github.com\electron-vuevite-quick-start\cmd\modules\release\index.
js not supported.
Instead change the require of E:\inBackup\MyCode\github.com\electron-vuevite-quick-start\node_modules\open\index
.js in E:\inBackup\MyCode\github.com\electron-vuevite-quick-start\cmd\modules\release\index.js to a dynamic impo
rt() which is available in all CommonJS modules.
    at Object.<anonymous> (E:\inBackup\MyCode\github.com\electron-vuevite-quick-start\cmd\modules\release\index.
js:3:14) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.20.4
/e/i/M/g/electron-vuevite-quick-start main• | 1 ❱

```

**Comment by heliomarpm** [comment]
Updated package versions

Thks

**Comment by heliomarpm** [comment]
Please leave me a star

**Comment by wildtang** [comment]
As I test today, This problem still exist, the newest code not resolve it.

```
PS E:\inBackup\MyCode\github.com\electron-vuevite-quick-start> git pull
Already up to date.
PS E:\inBackup\MyCode\github.com\electron-vuevite-quick-start> del .\node_modules\
Remove-Item: Cannot find path 'E:\inBackup\MyCode\github.com\electron-vuevite-quick-start\node_modules\' because it does not exist.
PS E:\inBackup\MyCode\github.com\electron-vuevite-quick-start> git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
PS E:\inBackup\MyCode\github.com\electron-vuevite-quick-start> git log -1
commit d04155644cf64bc5f744e34895cc749692960d30 (HEAD -> main, origin/main, origin/HEAD)
Author: Heliomar P. Marques <heliomarpm@gmail.com>
Date:   Sun Sep 29 21:47:27 2024 -0300

    ci: updated package versions
PS E:\inBackup\MyCode\github.com\electron-vuevite-quick-start> npm install
npm warn deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm warn deprecated npmlog@6.0.2: This package is no longer supported.
npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm warn deprecated gauge@4.0.4: This package is no longer supported.

added 447 packages, and audited 448 packages in 17s

74 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS E:\inBackup\MyCode\github.com\electron-vuevite-quick-start> npm run deploy

> electron-vuevite-quick-start@0.3.0 deploy
> node ./node_modules/gh_deploy/index.js

E:\inBackup\MyCode\github.com\electron-vuevite-quick-start\node_modules\gh_deploy\index.js:3
const open = require('open')
             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module E:\inBackup\MyCode\github.com\electron-vuevite-quick-start\node_modules\open\index.js from E:\inBackup\MyCode\github.com\electron-vuevite-quick-start\node_modules\gh_deploy\index.js not supported.
Instead change the require of E:\inBackup\MyCode\github.com\electron-vuevite-quick-start\node_modules\open\index.js in E:\inBackup\MyCode\github.com\electron-vuevite-quick-start\node_modules\gh_deploy\index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (E:\inBackup\MyCode\github.com\electron-vuevite-quick-start\node_modules\gh_deploy\index.js:3:14) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.17.0
PS E:\inBackup\MyCode\github.com\electron-vuevite-quick-start>
```

**Comment by heliomarpm** [comment]
> As I test today, This problem still exist, the newest code not resolve it.
> 
> ```
> PS E:\inBackup\MyCode\github.com\electron-vuevite-quick-start> git pull
> Already up to date.
> PS E:\inBackup\MyCode\github.com\electron-vuevite-quick-start> del .\node_modules\
> Remove-Item: Cannot find path 'E:\inBackup\MyCode\github.com\electron-vuevite-quick-start\node_modules\' because it does not exist.
> PS E:\inBackup\MyCode\github.com\electron-vuevite-quick-start> git status
> On branch main
> Your branch is up to date with 'origin/main'.
> 
> nothing to commit, working tree clean
> PS E:\inBackup\MyCode\github.com\electron-vuevite-quick-start> git log -1
> commit d04155644cf64bc5f744e34895cc749692960d30 (HEAD -> main, origin/main, origin/HEAD)
> Author: Heliomar P. Marques <heliomarpm@gmail.com>
> Date:   Sun Sep 29 21:47:27 2024 -0300
> 
>     ci: updated package versions
> PS E:\inBackup\MyCode\github.com\electron-vuevite-quick-start> npm install
> npm warn deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
> npm warn deprecated npmlog@6.0.2: This package is no longer supported.
> npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
> npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.
> npm warn deprecated gauge@4.0.4: This package is no longer supported.
> 
> added 447 packages, and audited 448 packages in 17s
> 
> 74 packages are looking for funding
>   run `npm fund` for details
> 
> found 0 vulnerabilities
> PS E:\inBackup\MyCode\github.com\electron-vuevite-quick-start> npm run deploy
> 
> > electron-vuevite-quick-start@0.3.0 deploy
> > node ./node_modules/gh_deploy/index.js
> 
> E:\inBackup\MyCode\github.com\electron-vuevite-quick-start\node_modules\gh_deploy\index.js:3
> const open = require('open')
>              ^
> 
> Error [ERR_REQUIRE_ESM]: require() of ES Module E:\inBackup\MyCode\github.com\electron-vuevite-quick-start\node_modules\open\index.js from E:\inBackup\MyCode\github.com\electron-vuevite-quick-start\node_modules\gh_deploy\index.js not supported.
> Instead change the require of E:\inBackup\MyCode\github.com\electron-vuevite-quick-start\node_modules\open\index.js in E:\inBackup\MyCode\github.com\electron-vuevite-quick-start\node_modules\gh_deploy\index.js to a dynamic import() which is available in all CommonJS modules.
>     at Object.<anonymous> (E:\inBackup\MyCode\github.com\electron-vuevite-quick-start\node_modules\gh_deploy\index.js:3:14) {
>   code: 'ERR_REQUIRE_ESM'
> }
> 
> Node.js v20.17.0
> PS E:\inBackup\MyCode\github.com\electron-vuevite-quick-start>
> ```

check your cloned repository, this index.js file is now index.mjs
